import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { ChapterCompositionPlanSchema } from "@/lib/domain/chapter-composition";
import { ProseGenerationConstraintsSchema } from "@/lib/domain/prose-generation-constraints";
import { CanonicalNarrativeGovernanceOrchestrationService } from "@/lib/services/canonical-narrative-governance-orchestration-service";

function minimalProse() {
  return ProseGenerationConstraintsSchema.parse({
    artifact: "prose_generation_constraints",
    proseConstraintId: "p1",
    chapterId: "book1-chapter-01",
    parentBeatChainId: "b1",
    parentChapterStateId: "book1-chapter-01",
    parentNarrativePsychologyId: "book1",
    povCharacterId: "pov-a",
    proseMode: "rooted_continuity",
    narrativeDistance: "close_externalized_embodied",
    cognitionMode: ["native_relational"],
    sentencePressureProfile: { level: "medium", compressionBias: 0.5 },
    sensoryDensityProfile: { requiredDensity: "high", requiredChannels: ["touch"] },
    environmentalGroundingFloor: 0.8,
    relationalSignalDensity: 0.6,
    memoryInvocationAllowance: 0.4,
    expositionAllowance: 0.1,
    interpretationAllowance: 0.2,
    ambiguityAllowance: 0.4,
    revelationAllowance: 0.2,
    emotionalLabelAllowance: 0.1,
    meaningReflectionAllowance: 0.2,
    lineTensionProfile: { target: "steady", unresolvedCarryForward: 0.6 },
    paragraphBreathProfile: { averageSentences: 4, allowedLongParagraphRatio: 0.2 },
    cadenceProfile: ["c"],
    dictionGuardrails: ["d"],
    syntaxGuardrails: ["s"],
    forbiddenPatterns: ["f"],
    requiredPatterns: ["r"],
    endingMomentumProfile: { vector: "carry", carryForwardPressureType: "warning" },
    literaryDeviceConstraints: {
      activeDeviceIds: [],
      suppressedDeviceIds: [],
      soundPatternAllowance: "minimal",
      symbolismAllowance: "minimal",
      metaphorSimileAllowance: "minimal",
      explicitnessCeiling: "low",
      closurePressureStyle: "state_pressure_seeded",
      callbackPhraseAllowance: false,
      placeMemoryInsertionOpportunities: [],
      repetitionAllowance: "rare_only",
    },
    continuityEmphasis: 0.7,
    placeImmersionTarget: 0.8,
    attachmentTarget: 0.75,
    driftFlags: [],
    validationFlags: [],
  });
}

describe("canonical-narrative-governance-orchestration-service", () => {
  it("applies cluster3 governance merge to base prose", () => {
    const plan = ChapterCompositionPlanSchema.parse({
      artifact: "chapter_composition_plan",
      schemaVersion: "1.0.0",
      compositionPlanId: "book1-chapter-01:plan",
      chapterId: "book1-chapter-01",
      parentBookId: "book1",
      parentNarrativePsychologyId: "book1",
      parentChapterStateId: "book1-chapter-01",
      activeThreadIds: ["thread-a"],
      latentThreadIds: [],
      callbackThreadIds: [],
      routeRequirementStatus: {
        requiredLocationIds: ["natchitoches"],
        missingLocationIds: [],
        recurrenceSatisfied: true,
        enforcementNotes: [],
      },
      philosophyRequirementStatus: {
        activePhilosophyThreadIds: ["thread-philosophy"],
        explicitnessCeiling: 0.2,
        satisfied: true,
        warnings: [],
      },
      compositionMode: "delayed_convergence",
      sceneCountTarget: 2,
      sceneSequence: [
        {
          scenePlanId: "scene-01",
          chapterId: "book1-chapter-01",
          sceneOrder: 1,
          sceneRole: "grounding_scene",
          povCandidateWeights: [{ povId: "pov-a", weight: 0.7 }],
          dominantThreadIds: ["thread-a"],
          secondaryThreadIds: [],
          latentThreadIds: [],
          settingBindings: ["natchitoches"],
          routeBindings: ["natchitoches"],
          philosophyBindings: [],
          callbackSeeds: [],
          delayedConvergenceKeys: [],
          requiredBeatBiases: { salience_lock_beat: 0.6 },
          requiredStateBiases: { unresolved_pull: 0.5 },
          apparentConnectionLevel: "apparently_isolated",
          actualConnectionLevel: "convergent_later",
          transitionStrategy: "soft_echo",
          carryForwardPressureType: "threaded_pressure",
          sceneClosureType: "open_knot",
          validationFlags: [],
        },
        {
          scenePlanId: "scene-02",
          chapterId: "book1-chapter-01",
          sceneOrder: 2,
          sceneRole: "closure_scene",
          povCandidateWeights: [{ povId: "pov-a", weight: 0.7 }],
          dominantThreadIds: ["thread-a"],
          secondaryThreadIds: [],
          latentThreadIds: [],
          settingBindings: ["natchitoches"],
          routeBindings: ["natchitoches"],
          philosophyBindings: [],
          callbackSeeds: [],
          delayedConvergenceKeys: [],
          requiredBeatBiases: { consequence_seed_beat: 0.5 },
          requiredStateBiases: { unresolved_pull: 0.8 },
          apparentConnectionLevel: "indirectly_linked",
          actualConnectionLevel: "hidden_linked",
          transitionStrategy: "closure_open",
          carryForwardPressureType: "threaded_pressure",
          sceneClosureType: "pressure_forward",
          validationFlags: [],
        },
      ],
      sceneContrastProfile: {
        tonalContrast: 0.6,
        pressureContrast: 0.62,
        threadMixContrast: 0.55,
        settingContrast: 0.3,
        notes: [],
      },
      delayedConvergenceBindings: [],
      callbackMarkers: [],
      reinterpretationAnchors: [],
      densityScore: 0.72,
      densityWarnings: [],
      routeCoverageNotes: [],
      continuityCarryForwardPlan: ["carry"],
      unresolvedPressurePlan: ["pressure"],
      chapterClosureProfile: "convergence_teased",
      validationFlags: [],
    });

    const result = new CanonicalNarrativeGovernanceOrchestrationService().orchestrate({
      proseConstraintsAfterLiteraryLayer: minimalProse(),
      epicId: "book1-epic",
      bookId: "book1",
      chapterId: "book1-chapter-01",
      chapterSequence: 1,
      chapterMode: "continuity_chapter",
      chapterPsychologyMode: "rooted_continuity",
      activeThreadIds: ["thread-a"],
      chapterCompositionPlan: plan,
      narrativeThreads: [],
      settingCoverageReport: { records: [], missingLocationIds: [] },
      sceneIdsInChapter: ["s1", "s2"],
      preparationPath: "book1_regeneration_orchestration",
    });

    assert.equal(result.proseConstraints.validationFlags.includes("cluster3_encs_eegs_narrator_governance_merge"), true);
    assert.equal(result.sequenceDerivation.bookSequencePlan.bookId, "book1");
  });
});
