import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { BeatAssemblyChainSchema } from "@/lib/domain/beat-assembly";
import { ChapterCompositionPlanSchema } from "@/lib/domain/chapter-composition";
import { ProseGenerationConstraintsSchema } from "@/lib/domain/prose-generation-constraints";
import { LiteraryDeviceDerivationService } from "@/lib/services/literary-device-derivation-service";
import { SceneGenerationEngineService } from "@/lib/services/scene-generation-engine-service";

describe("scene-generation-engine-service", () => {
  it("generates multi-scene bundles with transitions and preservation markers", () => {
    const chapterCompositionPlan = ChapterCompositionPlanSchema.parse({
      artifact: "chapter_composition_plan",
      schemaVersion: "1.0.0",
      compositionPlanId: "book1-chapter-01:plan",
      chapterId: "book1-chapter-01",
      parentBookId: "book1",
      parentNarrativePsychologyId: "book1",
      parentChapterStateId: "book1-chapter-01",
      activeThreadIds: ["thread-a", "thread-b"],
      latentThreadIds: ["thread-latent"],
      callbackThreadIds: ["thread-callback"],
      routeRequirementStatus: {
        requiredLocationIds: ["natchitoches"],
        missingLocationIds: [],
        recurrenceSatisfied: true,
        enforcementNotes: [],
      },
      philosophyRequirementStatus: {
        activePhilosophyThreadIds: ["thread-philosophy"],
        explicitnessCeiling: 0.2,
        satisfied: true,
        warnings: [],
      },
      compositionMode: "delayed_convergence",
      sceneCountTarget: 3,
      sceneSequence: [
        {
          scenePlanId: "scene-01",
          chapterId: "book1-chapter-01",
          sceneOrder: 1,
          sceneRole: "grounding_scene",
          povCandidateWeights: [{ povId: "pov-a", weight: 0.7 }],
          dominantThreadIds: ["thread-a"],
          secondaryThreadIds: [],
          latentThreadIds: ["thread-latent"],
          settingBindings: ["natchitoches"],
          routeBindings: ["natchitoches"],
          philosophyBindings: [],
          callbackSeeds: ["seed-1"],
          delayedConvergenceKeys: ["key-1"],
          requiredBeatBiases: { salience_lock_beat: 0.6 },
          requiredStateBiases: { unresolved_pull: 0.5 },
          apparentConnectionLevel: "apparently_isolated",
          actualConnectionLevel: "convergent_later",
          transitionStrategy: "soft_echo",
          carryForwardPressureType: "threaded_pressure",
          sceneClosureType: "open_knot",
          validationFlags: [],
        },
        {
          scenePlanId: "scene-02",
          chapterId: "book1-chapter-01",
          sceneOrder: 2,
          sceneRole: "rumor_scene",
          povCandidateWeights: [{ povId: "pov-a", weight: 0.7 }],
          dominantThreadIds: ["thread-b"],
          secondaryThreadIds: [],
          latentThreadIds: ["thread-latent"],
          settingBindings: ["natchitoches"],
          routeBindings: ["natchitoches"],
          philosophyBindings: ["thread-philosophy"],
          callbackSeeds: ["seed-2"],
          delayedConvergenceKeys: ["key-1"],
          requiredBeatBiases: { social_signal_beat: 0.6 },
          requiredStateBiases: { external_awareness: 0.7 },
          apparentConnectionLevel: "apparently_isolated",
          actualConnectionLevel: "convergent_later",
          transitionStrategy: "delayed_bind",
          carryForwardPressureType: "threaded_pressure",
          sceneClosureType: "open_knot",
          validationFlags: [],
        },
        {
          scenePlanId: "scene-03",
          chapterId: "book1-chapter-01",
          sceneOrder: 3,
          sceneRole: "closure_scene",
          povCandidateWeights: [{ povId: "pov-a", weight: 0.7 }],
          dominantThreadIds: ["thread-a", "thread-b"],
          secondaryThreadIds: [],
          latentThreadIds: [],
          settingBindings: ["natchitoches"],
          routeBindings: ["natchitoches"],
          philosophyBindings: ["thread-philosophy"],
          callbackSeeds: ["seed-3"],
          delayedConvergenceKeys: [],
          requiredBeatBiases: { consequence_seed_beat: 0.5 },
          requiredStateBiases: { unresolved_pull: 0.8 },
          apparentConnectionLevel: "indirectly_linked",
          actualConnectionLevel: "hidden_linked",
          transitionStrategy: "closure_open",
          carryForwardPressureType: "threaded_pressure",
          sceneClosureType: "pressure_forward",
          validationFlags: [],
        },
      ],
      sceneContrastProfile: {
        tonalContrast: 0.6,
        pressureContrast: 0.62,
        threadMixContrast: 0.55,
        settingContrast: 0.3,
        notes: [],
      },
      delayedConvergenceBindings: [],
      callbackMarkers: [
        {
          callbackId: "cb-1",
          sourceSceneId: "scene-01",
          sourceThreadId: "thread-a",
          callbackStrength: 0.6,
          callbackWindow: "chapter-03",
          callbackType: "warning_pattern",
          laterTargetOptions: ["scene-99"],
        },
      ],
      reinterpretationAnchors: [
        {
          reinterpretationAnchorId: "anchor-1",
          sourceSceneId: "scene-02",
          sourceThreadIds: ["thread-b"],
          originalPovId: "pov-a",
          alternatePovCandidates: ["pov-b"],
          reinterpretableElements: ["gesture missing context"],
          likelyMeaningShift: "rumor reframed as deliberate signal",
          hiddenInformationDelta: "withheld witness",
          reentryEligibilityWindow: "chapter-03",
          validationFlags: [],
        },
      ],
      densityScore: 0.72,
      densityWarnings: [],
      routeCoverageNotes: [],
      continuityCarryForwardPlan: ["carry"],
      unresolvedPressurePlan: ["pressure"],
      chapterClosureProfile: "convergence_teased",
      validationFlags: [],
    });

    const chapterConstraints = ProseGenerationConstraintsSchema.parse({
      artifact: "prose_generation_constraints",
      proseConstraintId: "constraints-1",
      chapterId: "book1-chapter-01",
      parentBeatChainId: "beat-chain-1",
      parentChapterStateId: "book1-chapter-01",
      parentNarrativePsychologyId: "book1",
      povCharacterId: "pov-a",
      proseMode: "rooted_continuity",
      narrativeDistance: "close_externalized_embodied",
      cognitionMode: ["native_relational"],
      sentencePressureProfile: { level: "medium", compressionBias: 0.5 },
      sensoryDensityProfile: { requiredDensity: "high", requiredChannels: ["touch"] },
      environmentalGroundingFloor: 0.8,
      relationalSignalDensity: 0.6,
      memoryInvocationAllowance: 0.5,
      expositionAllowance: 0.1,
      interpretationAllowance: 0.3,
      ambiguityAllowance: 0.4,
      revelationAllowance: 0.25,
      emotionalLabelAllowance: 0.1,
      meaningReflectionAllowance: 0.2,
      lineTensionProfile: { target: "steady", unresolvedCarryForward: 0.6 },
      paragraphBreathProfile: { averageSentences: 4, allowedLongParagraphRatio: 0.2 },
      cadenceProfile: ["cadence"],
      dictionGuardrails: ["guardrail"],
      syntaxGuardrails: ["syntax"],
      forbiddenPatterns: ["forbidden"],
      requiredPatterns: ["required"],
      endingMomentumProfile: { vector: "convergence", carryForwardPressureType: "warning" },
      literaryDeviceConstraints: {
        activeDeviceIds: [],
        suppressedDeviceIds: [],
        soundPatternAllowance: "minimal",
        symbolismAllowance: "minimal",
        metaphorSimileAllowance: "minimal",
        explicitnessCeiling: "low",
        closurePressureStyle: "state_pressure_seeded",
        callbackPhraseAllowance: false,
        placeMemoryInsertionOpportunities: [],
        repetitionAllowance: "rare_only",
      },
      continuityEmphasis: 0.7,
      placeImmersionTarget: 0.8,
      attachmentTarget: 0.7,
      driftFlags: [],
      validationFlags: [],
    });

    const beatChain = BeatAssemblyChainSchema.parse({
      artifact: "beat-chain-1",
      schemaVersion: "1.0.0",
      chapter: 1,
      generatedAt: new Date().toISOString(),
      worldviewFrame: {
        storyLocale: "natchitoches",
        eraWindow: "pre-displacement",
        cognitionTranslationMode: "native_cognition_first_translated_to_english",
        runtimeBoundary: "metaphysical_and_cosmic_drivers_fenced_off",
      },
      transitionRules: {
        allowed: {
          salience_lock_beat: ["environmental_confirmation_beat"],
          memory_comparison_beat: ["social_signal_beat"],
          environmental_confirmation_beat: ["memory_comparison_beat"],
          emotional_appraisal_beat: ["micro_decision_beat"],
          micro_decision_beat: ["consequence_seed_beat"],
          social_signal_beat: ["relational_interpretation_beat"],
          relational_interpretation_beat: ["emotional_appraisal_beat"],
          pressure_escalation_beat: ["state_update_beat"],
          meaning_trace_beat: ["consequence_seed_beat"],
          consequence_seed_beat: ["state_update_beat"],
          state_update_beat: ["salience_lock_beat"],
        },
        disallowed: {
          salience_lock_beat: [],
          memory_comparison_beat: [],
          environmental_confirmation_beat: [],
          emotional_appraisal_beat: [],
          micro_decision_beat: [],
          social_signal_beat: [],
          relational_interpretation_beat: [],
          pressure_escalation_beat: [],
          meaning_trace_beat: [],
          consequence_seed_beat: [],
          state_update_beat: [],
        },
      },
      beats: Array.from({ length: 8 }, (_, index) => ({
        beatId: `beat-${index + 1}`,
        beatType: index === 0 ? "salience_lock_beat" : index % 2 === 0 ? "social_signal_beat" : "consequence_seed_beat",
        beatPurpose: "purpose",
        povCharacterId: "pov-a",
        temporalPosition: { chapter: 1, sequence: index + 1, phaseLabel: "phase", timeOfDay: "dawn" },
        locationContext: { zone: "zone", environment: "env" },
        physicalAction: "action",
        environmentalSignal: "signal",
        sensorySignal: "sensory",
        socialSignal: "social",
        interpretedMeaning: "meaning",
        emotionVector: { primary: "duty", valence: 0.2, arousal: 0.6, socialRisk: 0.4, containment: 0.5 },
        memoryTriggered: "memory",
        decisionOrAdjustment: "adjustment",
        downstreamRisk: "risk",
        stateUpdate: "state update",
        salienceReason: "salience",
        visibilityScope: { locallyKnown: ["pov-a"], globallyKnownButHiddenFromPov: [] },
        confidence: 0.8,
        pressureLoad: 0.5,
        validationFlags: {
          physicallyGrounded: true,
          observerBounded: true,
          salienceJustified: true,
          modernCognitionLeakFree: true,
          hasStateConsequence: true,
          chapterOneEscalationSafe: true,
          runtimeBoundarySafe: true,
          notes: [],
        },
      })),
      chainValidation: { passed: true, invalidReasons: [] },
      provenance: { sourceArtifacts: ["test"] },
    });

    const literaryPack = new LiteraryDeviceDerivationService().buildBook1SamplePack({
      chapterId: "book1-chapter-01",
      sceneId: "scene-01",
      sceneRoles: chapterCompositionPlan.sceneSequence.map((scene) => scene.sceneRole),
      beatTypes: beatChain.beats.map((beat) => beat.beatType),
      chapterPsychologyMode: "rooted_continuity",
      chapterMode: "continuity_chapter",
    });

    const result = new SceneGenerationEngineService().run({
      chapterId: "book1-chapter-01",
      parentBookId: "book1",
      parentChapterStateId: "book1-chapter-01",
      parentNarrativePsychologyId: "book1",
      chapterCompositionPlan,
      sequencePlanId: "book1-sequence",
      activeThreadPackId: "thread-pack-1",
      routeLedgerSnapshot: { natchitoches: true },
      philosophyPropagationPlanId: "phil-1",
      callbackPlanId: "cb-1",
      reinterpretationAnchorSetId: "anchor-set-1",
      chapterLevelProseConstraints: chapterConstraints,
      chapterMode: "continuity_chapter",
      chapterPsychologyMode: "rooted_continuity",
      chapterLevelLiteraryControlSettings: literaryPack.controlSettings,
      chapterLevelLiteraryDevicePlan: literaryPack.scenePlans[0] ?? {},
      beatChain,
    });

    assert.equal(result.bundle.generatedScenes.length, 3);
    assert.equal(result.bundle.generatedScenes[1]?.sceneRole, "rumor_scene");
    assert.equal(result.bundle.generatedScenes.some((scene) => scene.delayedConvergenceKeysPresent.length > 0), true);
    assert.equal(result.bundle.generatedScenes.some((scene) => scene.callbackSeedsTriggered.length > 0), true);
    assert.equal(result.bundle.generatedScenes.some((scene) => scene.reinterpretationAnchorsPresent.length > 0), true);
    assert.equal(result.bundle.runtimeAuthority.isCanonicalProduction, true);
    assert.equal(result.bundle.generatedScenes.every((scene) => scene.runtimeAuthority.isCanonicalProduction), true);
    assert.equal(result.bundle.adjacencySummary.length >= 2, true);
    assert.equal(result.validation.hardFailures.includes("callback_plan_loss"), false);
  });
});

