import assert from "node:assert/strict";
import { describe, it } from "node:test";

import { ChapterCompositionPlanSchema } from "@/lib/domain/chapter-composition";
import { ProseGenerationConstraintsSchema } from "@/lib/domain/prose-generation-constraints";
import { SceneGenerationRequestDerivationService } from "@/lib/services/scene-generation-request-derivation-service";

describe("scene-generation-request-derivation-service", () => {
  it("derives a machine-usable scene generation request from chapter truth", () => {
    const chapterCompositionPlan = ChapterCompositionPlanSchema.parse({
      artifact: "chapter_composition_plan",
      schemaVersion: "1.0.0",
      compositionPlanId: "book1-chapter-01:plan",
      chapterId: "book1-chapter-01",
      parentBookId: "book1",
      parentNarrativePsychologyId: "book1",
      parentChapterStateId: "book1-chapter-01",
      activeThreadIds: ["thread-a"],
      latentThreadIds: ["thread-b"],
      callbackThreadIds: ["thread-c"],
      routeRequirementStatus: {
        requiredLocationIds: ["natchitoches"],
        missingLocationIds: [],
        recurrenceSatisfied: true,
        enforcementNotes: [],
      },
      philosophyRequirementStatus: {
        activePhilosophyThreadIds: ["thread-philosophy"],
        explicitnessCeiling: 0.25,
        satisfied: true,
        warnings: [],
      },
      compositionMode: "delayed_convergence",
      sceneCountTarget: 2,
      sceneSequence: [
        {
          scenePlanId: "scene-01",
          chapterId: "book1-chapter-01",
          sceneOrder: 1,
          sceneRole: "grounding_scene",
          povCandidateWeights: [{ povId: "pov-a", weight: 0.7 }],
          dominantThreadIds: ["thread-a"],
          secondaryThreadIds: [],
          latentThreadIds: ["thread-b"],
          settingBindings: ["natchitoches"],
          routeBindings: ["natchitoches"],
          philosophyBindings: [],
          callbackSeeds: ["seed-1"],
          delayedConvergenceKeys: ["key-1"],
          requiredBeatBiases: { salience_lock_beat: 0.6 },
          requiredStateBiases: { unresolved_pull: 0.5 },
          apparentConnectionLevel: "apparently_isolated",
          actualConnectionLevel: "convergent_later",
          transitionStrategy: "delayed-bind",
          carryForwardPressureType: "threaded_pressure",
          sceneClosureType: "open_knot",
          validationFlags: [],
        },
        {
          scenePlanId: "scene-02",
          chapterId: "book1-chapter-01",
          sceneOrder: 2,
          sceneRole: "closure_scene",
          povCandidateWeights: [{ povId: "pov-a", weight: 0.7 }],
          dominantThreadIds: ["thread-a"],
          secondaryThreadIds: [],
          latentThreadIds: [],
          settingBindings: ["natchitoches"],
          routeBindings: ["natchitoches"],
          philosophyBindings: [],
          callbackSeeds: [],
          delayedConvergenceKeys: [],
          requiredBeatBiases: { consequence_seed_beat: 0.5 },
          requiredStateBiases: { unresolved_pull: 0.7 },
          apparentConnectionLevel: "indirectly_linked",
          actualConnectionLevel: "hidden_linked",
          transitionStrategy: "closure-open",
          carryForwardPressureType: "threaded_pressure",
          sceneClosureType: "pressure_forward",
          validationFlags: [],
        },
      ],
      sceneContrastProfile: {
        tonalContrast: 0.5,
        pressureContrast: 0.55,
        threadMixContrast: 0.45,
        settingContrast: 0.3,
        notes: [],
      },
      delayedConvergenceBindings: [],
      callbackMarkers: [],
      reinterpretationAnchors: [],
      densityScore: 0.7,
      densityWarnings: [],
      routeCoverageNotes: [],
      continuityCarryForwardPlan: ["keep pressure unresolved"],
      unresolvedPressurePlan: ["route pressure"],
      chapterClosureProfile: "convergence_teased",
      validationFlags: [],
    });
    const constraints = ProseGenerationConstraintsSchema.parse({
      artifact: "prose_generation_constraints",
      proseConstraintId: "constraints-1",
      chapterId: "book1-chapter-01",
      parentBeatChainId: "beat-chain-1",
      parentChapterStateId: "book1-chapter-01",
      parentNarrativePsychologyId: "book1",
      povCharacterId: "pov-a",
      proseMode: "rooted_continuity",
      narrativeDistance: "close_externalized_embodied",
      cognitionMode: ["native_relational"],
      sentencePressureProfile: { level: "medium", compressionBias: 0.5 },
      sensoryDensityProfile: { requiredDensity: "high", requiredChannels: ["touch"] },
      environmentalGroundingFloor: 0.7,
      relationalSignalDensity: 0.6,
      memoryInvocationAllowance: 0.5,
      expositionAllowance: 0.12,
      interpretationAllowance: 0.3,
      ambiguityAllowance: 0.4,
      revelationAllowance: 0.25,
      emotionalLabelAllowance: 0.1,
      meaningReflectionAllowance: 0.2,
      lineTensionProfile: { target: "steady", unresolvedCarryForward: 0.6 },
      paragraphBreathProfile: { averageSentences: 4, allowedLongParagraphRatio: 0.2 },
      cadenceProfile: ["cadence"],
      dictionGuardrails: ["guardrail"],
      syntaxGuardrails: ["syntax"],
      forbiddenPatterns: ["forbidden"],
      requiredPatterns: ["required"],
      endingMomentumProfile: { vector: "convergence", carryForwardPressureType: "warning" },
      literaryDeviceConstraints: {
        activeDeviceIds: [],
        suppressedDeviceIds: [],
        soundPatternAllowance: "minimal",
        symbolismAllowance: "minimal",
        metaphorSimileAllowance: "minimal",
        explicitnessCeiling: "low",
        closurePressureStyle: "state_pressure_seeded",
        callbackPhraseAllowance: false,
        placeMemoryInsertionOpportunities: [],
        repetitionAllowance: "rare_only",
      },
      continuityEmphasis: 0.7,
      placeImmersionTarget: 0.8,
      attachmentTarget: 0.7,
      driftFlags: [],
      validationFlags: [],
    });

    const request = new SceneGenerationRequestDerivationService().derive({
      chapterId: "book1-chapter-01",
      parentBookId: "book1",
      parentChapterStateId: "book1-chapter-01",
      parentNarrativePsychologyId: "book1",
      chapterCompositionPlan,
      sequencePlanId: "book1-sequence",
      activeThreadPackId: "thread-pack-1",
      routeLedgerSnapshot: { natchitoches: true },
      philosophyPropagationPlanId: "phil-1",
      callbackPlanId: "cb-1",
      reinterpretationAnchorSetId: "re-1",
      chapterLevelProseConstraints: constraints,
      chapterLevelLiteraryDevicePlan: { activeDeviceIds: [] },
    });

    assert.equal(request.chapterId, "book1-chapter-01");
    assert.equal(request.scenePlanSequence.length, 2);
    assert.equal(request.parentSequencePlanId, "book1-sequence");
    assert.equal(request.validationFlags.includes("composition_truth_consumed"), true);
  });
});

