/** Starter clichés / workshop filler—extend via DB or config later. */
export const CLICHE_PHRASES: readonly string[] = [
  "at the end of the day",
  "it goes without saying",
  "needless to say",
  "in this day and age",
  "only time will tell",
  "time will tell",
  "the fact of the matter",
  "each and every",
  "first and foremost",
  "last but not least",
  "when all is said and done",
  "avoid like the plague",
  "read between the lines",
  "play devil's advocate",
  "think outside the box",
  "paradigm shift",
  "on the same page",
  "push the envelope",
  "low-hanging fruit",
  "move the needle",
  "at the crack of dawn",
  "dead of night",
  "cold as ice",
  "quiet as a mouse",
  "busy as a bee",
  "crystal clear",
  "fade into oblivion",
  "heart skipped a beat",
  "blood ran cold",
  "breath they didn't know they were holding",
  "chills ran down",
  "piercing blue eyes",
  "raven hair",
  "orbs instead of eyes",
  "for a moment that felt like hours",
  "world faded away",
  "something shifted",
  "something fundamental",
  "in that instant",
  "everything changed",
  "little did they know",
  "little did she know",
  "little did he know",
  "couldn't help but",
  "couldn't help but feel",
  "a single tear",
  "tears welled",
  "heart hammered",
  "stomach dropped",
  "time seemed to slow",
  "time stood still",
  "the silence stretched",
  "thick with tension",
  "heavy silence",
  "palpable tension",
  "cut the tension with a knife",
  "shivered despite",
  "despite themselves",
  "despite herself",
  "despite himself",
];

/** Abstract / evaluative nouns—high density can signal telling-not-showing (heuristic). */
export const ABSTRACT_NOUNS: ReadonlySet<string> = new Set([
  "thing",
  "things",
  "situation",
  "moment",
  "feeling",
  "sense",
  "awareness",
  "realization",
  "understanding",
  "connection",
  "relationship",
  "dynamic",
  "tension",
  "emotion",
  "emotions",
  "truth",
  "meaning",
  "fate",
  "destiny",
  "justice",
  "freedom",
  "power",
  "history",
  "memory",
  "silence",
  "hope",
  "fear",
  "love",
  "grief",
  "trauma",
  "identity",
  "belonging",
]);

/** Concrete sensory channels—presence suggests embodied prose (heuristic). */
export const SENSORY_LEXICON: ReadonlySet<string> = new Set([
  "mud",
  "clay",
  "iron",
  "oak",
  "pine",
  "cypress",
  "moss",
  "salt",
  "sweat",
  "blood",
  "skin",
  "throat",
  "palm",
  "knuckle",
  "heat",
  "cold",
  "damp",
  "dust",
  "smoke",
  "ash",
  "river",
  "water",
  "cotton",
  "leather",
  "rope",
  "blister",
  "callus",
  "cricket",
  "dog",
  "horse",
  "mule",
  "rain",
  "thunder",
  "cicada",
  "resin",
  "tar",
  "sawdust",
  "cornmeal",
  "coffee",
  "molasses",
  "lard",
  "kerosene",
]);

export const STOPWORDS: ReadonlySet<string> = new Set([
  "the",
  "a",
  "an",
  "and",
  "or",
  "but",
  "in",
  "on",
  "at",
  "to",
  "for",
  "of",
  "as",
  "by",
  "with",
  "from",
  "into",
  "was",
  "were",
  "is",
  "are",
  "be",
  "been",
  "being",
  "had",
  "has",
  "have",
  "it",
  "its",
  "their",
  "they",
  "them",
  "he",
  "she",
  "his",
  "her",
  "that",
  "this",
  "there",
  "then",
  "than",
]);
