import type { CamptiBuildStage } from "./types";

/**
 * Cursor execution order: one stage at a time.
 * Do not build UI-first — follow: law → ontology → variables → engines → admin → gates → simulation runs.
 */
export const CAMPTI_BUILD_STAGES: CamptiBuildStage[] = [
  {
    stage: 1,
    id: "constitutional-core",
    title: "Constitutional Core",
    promptLabel: "CAMPTI STAGE 1 — CONSTITUTIONAL CORE",
    layerFocus: "Governing law of the system before anything else expands.",
    modelsToBuild: [
      "ConstitutionalRule",
      "DeterminismPolicy",
      "TruthPolicy",
      "AmbiguityPolicy",
      "RevealPolicy",
      "VoicePolicy",
      "ViolencePolicy",
      "TheologyPolicy",
      "DraftEligibilityPolicy",
    ],
    adminSurfaces: [
      "/admin/narrative-rules",
      "/admin/continuity",
      "/admin/questions",
      "/admin/bindings",
      "/admin/brain",
    ],
    goal: "No narrative object exists without legal status.",
    antiPatterns: ["Skipping to generation features", "UI before schema"],
  },
  {
    stage: 2,
    id: "ontology-registry-spine",
    title: "Ontology / Registry Spine",
    promptLabel: "CAMPTI STAGE 2 — ONTOLOGY AND REGISTRY SPINE",
    layerFocus: "What kinds of things can exist; every object inherits from a known ontology.",
    modelsToBuild: [
      "Entity type registry",
      "Record type registry",
      "Visibility states",
      "Confidence states",
      "Narrative permission states",
      "Branch states",
      "Pressure states",
      "Scene readiness states",
      "Symbolic categories",
      "Relationship categories",
      "Environment categories",
    ],
    adminSurfaces: ["/admin/registries", "/admin/brain"],
    goal: "Every object inherits from a known ontology.",
  },
  {
    stage: 3,
    id: "character-engine",
    title: "Character Engine",
    promptLabel: "CAMPTI STAGE 3 — CHARACTER ENGINE",
    layerFocus: "Characters as bounded simulation systems, not static descriptions.",
    modelsToBuild: [
      "CharacterProfile (extend)",
      "CharacterState (extend)",
      "CharacterConstraint",
      "CharacterTrigger",
      "CharacterPerceptionProfile",
      "CharacterVoiceProfile",
      "CharacterChoiceProfile",
      "CharacterNeedStack",
      "CharacterArcVector",
      "CharacterMask",
    ],
    adminSurfaces: ["/admin/people", "/admin/characters/[id]/mind", "/admin/relationships"],
    goal: "Characters become decision engines with thresholds, triggers, and lawful choice bandwidth.",
  },
  {
    stage: 4,
    id: "place-environment-engine",
    title: "Place / Environment Engine",
    promptLabel: "CAMPTI STAGE 4 — PLACE AND ENVIRONMENT ENGINE",
    layerFocus: "Land governs behavior, perception, risk, and memory.",
    modelsToBuild: [
      "PlaceState",
      "EnvironmentProfile",
      "CorridorRoute",
      "ThresholdZone",
      "RiskRegime",
      "SensoryProfile",
      "SocialMovementRules",
      "WeatherBehavior",
      "SeasonalityProfile",
    ],
    adminSurfaces: ["/admin/places", "/admin/places/[id]/environment", "/admin/trade-corridors (future)", "/admin/risk-regimes (future)"],
    goal: "Place changes what can be seen, said, remembered, and survived.",
  },
  {
    stage: 5,
    id: "pressure-historical-order",
    title: "Pressure / Historical Order Engine",
    promptLabel: "CAMPTI STAGE 5 — PRESSURE AND HISTORICAL ORDER ENGINE",
    layerFocus: "External forces that compress choice before characters choose.",
    modelsToBuild: [
      "PressureField",
      "LegalRegime",
      "RaceNamingRules",
      "ChurchAuthorityProfile",
      "EconomicPressureProfile",
      "GenderObligationProfile",
      "SurveillanceProfile",
      "PunishmentVectors",
      "ReputationLogic",
    ],
    adminSurfaces: ["/admin/brain", "/admin/events", "/admin/questions"],
    goal: "The world defines the shape of thinkable choice before characters choose.",
  },
  {
    stage: 5.5,
    id: "intelligence-knowledge-horizon",
    title: "Intelligence, Knowledge Horizon & Maturity Engine",
    promptLabel: "CAMPTI STAGE 5.5 — INTELLIGENCE, KNOWLEDGE HORIZON AND MATURITY ENGINE",
    layerFocus:
      "Before relationship/desire engines, bound cognition: what can be noticed, understood, and said under era, body, and training — not a single IQ scalar.",
    modelsToBuild: [
      "WorldKnowledgeProfile",
      "WorldExpressionProfile",
      "CharacterIntelligenceProfile",
      "CharacterDevelopmentProfile",
      "CharacterBiologicalState",
      "evaluateCharacterKnowledgeHorizon / assembleCharacterCognitiveEnvelope (simulation stubs)",
    ],
    adminSurfaces: ["/admin/world-states/[id]/knowledge", "/admin/characters/[id]/intelligence"],
    goal: "Inference is substrate-only; the character’s mind is historically and biologically bounded.",
    antiPatterns: ["Letting the model speak with modern therapy or academic abstraction in premodern minds", "Collapsing intelligence to one number"],
  },
  {
    stage: 6.1,
    id: "relationship-desire-masking",
    title: "Relationship, Desire & Masking Engine",
    promptLabel: "CAMPTI STAGE 6 — RELATIONSHIP, DESIRE AND MASKING ENGINE",
    layerFocus:
      "Human collision: bonds, desire, masking, disclosure, and network summaries under world norms—not abstract dyads.",
    modelsToBuild: [
      "RelationshipProfile",
      "RelationshipDynamicState",
      "CharacterMaskingProfile",
      "CharacterDesireProfile",
      "WorldRelationshipNormProfile",
      "RelationshipDisclosureProfile",
      "RelationshipNetworkSummary",
    ],
    adminSurfaces: [
      "/admin/relationships",
      "/admin/world-states/[id]/relationships",
      "/admin/characters/[id]/relationships",
    ],
    goal: "What people feel, want, hide, and risk when revealing—between bounded minds under pressure.",
    antiPatterns: ["Gossip/reputation simulation before schema exists", "Trauma or prose engines in this stage"],
  },
  {
    stage: 6.5,
    id: "trauma-consequence-rumor-education",
    title: "Trauma, Health, Consequence Memory, Rumor & Education Engine",
    promptLabel: "CAMPTI STAGE 6.5 — TRAUMA, HEALTH, CONSEQUENCE, RUMOR AND EDUCATION",
    layerFocus:
      "Continuity over time: pain, world-shaped health (body/mind/emotion), learned rules, rumor, training — still not simulation runs.",
    modelsToBuild: [
      "CharacterTraumaProfile",
      "CharacterConsequenceMemoryProfile",
      "CharacterRumorReputationProfile",
      "WorldEducationNormProfile",
      "CharacterEducationProfile",
      "CharacterLearningEnvelope",
      "WorldHealthNormProfile",
      "CharacterPhysicalHealthProfile",
      "CharacterMentalHealthProfile",
      "CharacterEmotionalHealthProfile",
      "CharacterHealthEnvelope",
    ],
    adminSurfaces: [
      "/admin/characters/[id]/continuity",
      "/admin/world-states/[id]/education",
      "/admin/world-states/[id]/health",
      "/admin/continuity/education",
    ],
    goal: "Bodies and minds stay real; interpretation and care are era-shaped — behavior changes because state is encoded.",
    antiPatterns: ["DSM-first labeling as world UI", "Spiritual engine", "Prose generation", "Full scene simulation in this stage"],
  },
  {
    stage: 6,
    id: "symbol-motif-law",
    title: "Symbol / Motif Law Engine",
    promptLabel: "CAMPTI STAGE 6 — SYMBOL AND MOTIF LAW ENGINE",
    layerFocus: "Formal symbolic grammar — governed meaning-carriers.",
    modelsToBuild: [
      "SymbolLaw",
      "MotifLaw",
      "SymbolActivationCondition",
      "SymbolTransformationPath",
      "MotifRecurrencePlan",
      "SymbolSceneBinding",
      "SymbolCharacterBinding",
    ],
    adminSurfaces: ["/admin/symbols", "/admin/motifs", "/admin/bindings"],
    goal: "Symbols become governed meaning-carriers, not repeated imagery.",
  },
  {
    stage: 7,
    id: "timeline-anchor",
    title: "Timeline / Anchor Engine",
    promptLabel: "CAMPTI STAGE 7 — TIMELINE AND ANCHOR ENGINE",
    layerFocus: "Temporal determinism — fixed and elastic moments.",
    modelsToBuild: [
      "TimelineNode",
      "SimulationAnchor",
      "SoftAnchor",
      "HiddenAnchor",
      "PivotCycle",
      "IrreversibleEvent",
      "ConvergenceNode",
      "TemporalVarianceRule",
      "BranchWindow",
    ],
    adminSurfaces: ["/admin/events", "/admin/chapters", "/admin/scenes", "/admin/simulation-anchors (future)", "/admin/cycles (future)"],
    goal: "Time becomes a structured field of fixed and elastic moments.",
  },
  {
    stage: 8,
    id: "scene-constraint",
    title: "Scene Constraint Engine",
    promptLabel: "CAMPTI STAGE 8 — SCENE CONSTRAINT ENGINE",
    layerFocus: "Scene simulation law — legality before prose.",
    modelsToBuild: [
      "SceneState",
      "SceneConstraintSet",
      "ScenePressureMap",
      "ScenePerceptionMap",
      "SceneObjectiveMap",
      "SceneRevealBudget",
      "SceneSymbolBindings",
      "SceneOutcomeEnvelope",
      "SceneBranchTable",
      "SceneReadiness",
    ],
    adminSurfaces: ["/admin/scenes", "/admin/scenes/[id]/workspace", "/admin/meta-scenes", "/admin/scene-readiness (future)"],
    goal: "A scene can only be simulated if its legality is defined.",
  },
  {
    stage: 9,
    id: "meta-scene-experience",
    title: "Meta-Scene / Experience Engine",
    promptLabel: "CAMPTI STAGE 9 — META-SCENE AND EXPERIENCE ENGINE",
    layerFocus: "Separate event truth from reader experience.",
    modelsToBuild: [
      "MetaSceneState",
      "PerceptionTuning",
      "ExperienceTuning",
      "CinematicPass",
      "ViewModeProfile",
      "IntimacyProfile",
      "MysteryDensityProfile",
    ],
    adminSurfaces: [
      "/admin/meta-scenes/[id]/compose",
      "/admin/meta-scenes/[id]/perception",
      "/admin/meta-scenes/[id]/experience-tuning",
      "/admin/meta-scenes/[id]/cinematic",
      "/admin/meta-scenes/[id]/view",
    ],
    goal: "The same event can be rendered differently without breaking the truth model.",
  },
  {
    stage: 10,
    id: "voice-governance",
    title: "Voice Governance Engine",
    promptLabel: "CAMPTI STAGE 10 — VOICE GOVERNANCE ENGINE",
    layerFocus: "Rule-bound language so AI cannot flatten voice.",
    modelsToBuild: [
      "VoiceProfile (extend)",
      "RegisterProfile",
      "DictionRules",
      "SyntaxRules",
      "DialectHandlingRules",
      "MetaphorPermissions",
      "NarratorVisibilityRules",
      "AntiSmoothingRules",
    ],
    adminSurfaces: ["/admin/voice-profiles (future)", "/admin/pov-governors (future)", "/admin/reveal-architecture (future)"],
    goal: "Language becomes governed output, not generic AI style.",
  },
  {
    stage: 11,
    id: "memory-fragment",
    title: "Memory / Fragment Engine",
    promptLabel: "CAMPTI STAGE 11 — MEMORY AND FRAGMENT ENGINE",
    layerFocus: "Non-linear memory infrastructure under law.",
    modelsToBuild: [
      "MemoryUnit",
      "InheritedMemory",
      "ObjectMemory",
      "LandMemory",
      "TraumaticRecurrence",
      "ArchiveRediscovery",
      "MemoryTrigger",
      "FragmentCluster (extend)",
    ],
    adminSurfaces: ["/admin/fragments", "/admin/clusters", "/admin/sources/[id]/decompose"],
    goal: "The story moves through memory lawfully, not randomly.",
  },
  {
    stage: 12,
    id: "branch-determinism",
    title: "Branch / Determinism Engine",
    promptLabel: "CAMPTI STAGE 12 — BRANCH AND DETERMINISM ENGINE",
    layerFocus: "Explicit simulation logic — legal path space.",
    modelsToBuild: [
      "BranchCondition",
      "BranchOutcome",
      "VariableSet",
      "RunProfile",
      "ScenarioSlice",
      "ChoiceBandwidth",
      "CollapseCondition",
      "DeterministicConstraint",
    ],
    adminSurfaces: ["/admin/brain", "/admin/bindings", "/admin/branch-conditions (future)", "/admin/choice-profiles (future)"],
    goal: "AI explores legal path space rather than inventing options from nowhere.",
  },
  {
    stage: 13,
    id: "research-story-binding",
    title: "Research-to-Story Binding Engine",
    promptLabel: "CAMPTI STAGE 13 — RESEARCH TO STORY BINDING ENGINE",
    layerFocus: "Archive → narrative fuel with traceable truth flow.",
    modelsToBuild: [
      "SourceSupportLevel (formalize)",
      "StorySupportLevel",
      "NarrativeBinding (extend)",
      "SceneSupportObject",
      "CanonicalBinding",
      "ClaimUsageRule",
      "QuoteEligibilityRule",
    ],
    adminSurfaces: ["/admin/sources", "/admin/ingestion", "/admin/extracted", "/admin/bindings", "/admin/fragments"],
    goal: "Every story-support object knows how much truth can legally flow into prose.",
  },
  {
    stage: 14,
    id: "composition-readiness",
    title: "Composition Readiness Engine",
    promptLabel: "CAMPTI STAGE 14 — COMPOSITION READINESS ENGINE",
    layerFocus: "Gates — no prose generation before readiness exists.",
    modelsToBuild: [
      "DraftReadinessValidator",
      "SceneEligibilityMatrix",
      "MissingDependencyReport",
      "ProsePermissionState",
    ],
    adminSurfaces: ["/admin/scene-readiness (future)", "/admin/scenes/[id]/workspace"],
    goal: "No scene gets drafted until the engine says it is ready.",
  },
  {
    stage: 15,
    id: "simulation-run-layer",
    title: "Simulation Run Layer",
    promptLabel: "CAMPTI STAGE 15 — SIMULATION RUN LAYER",
    layerFocus: "Runnable scenarios, snapshots, trace — after lower layers exist.",
    modelsToBuild: [
      "SimulationRun",
      "SimulationSnapshot",
      "VariableSnapshot",
      "RunWarnings",
      "RunTrace",
      "AlternatePathRecord",
    ],
    adminSurfaces: ["/admin/brain (future run console)", "/admin/simulation-runs (future)"],
    goal: "Campti runs scenario slices, compares legal paths, preserves traceability.",
  },
];
